export { default as getAvaterObj } from './avatars'
export { default as geticonObj } from './icons'
export { default as SelectedSvg } from './selectedSvg'
export { default as SvgSlider } from './Slider'
export { default as SlideItems } from './slideItems'
export { default as SliderAction } from './slideAction'