import { Inter } from "next/font/google";
import { ChakraProviders } from "./providers";
import Navber from "@/components/common/navber";
import Provider from "@/redux/provider";
import type { Metadata } from "next";
import Layout from "@/components/common/layout";
import Setup from "@/components/utills/setup";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Setup/>
          <ChakraProviders>
            <div style={{width:'100vw'}}>
              <Navber />
              <Layout >
                {children}
              </Layout>
            </div>
          </ChakraProviders>
        </Provider>
      </body>
    </html>
  );
}
