import { ChakraProviders } from "./providers";
import Navbar from "@/components/common/navbar";
import Provider from "@/redux/provider";
import type { Metadata } from "next";
import Layout from "@/components/common/layout";
import { Setup } from "@/components/utils";
export const metadata: Metadata = {
  title: process.env.APP_NAME,
  description: "Generated by create next app",
};
import { CSSReset } from "@chakra-ui/react";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Setup/>
          <ChakraProviders>
            <div style={{width:'100vw'}}>
              <Navbar />
              <Layout >
                {children}
              </Layout>
            </div>
          </ChakraProviders>
        </Provider>
      </body>
    </html>
  );
}
